## Configuration file for DWGettingStarted application.
---
# User login.
login: javaeeeee
# User  password.
password: crimson

#Server configuration.
server:
    applicationConnectors:
        - type: http
          port: 8080
        - type: https
          port: 8443
          keyStorePath: dwstart.keystore
          keyStorePassword: crimson
          validateCerts: false
          validatePeers: false

# Database settings.
database:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: root
    # the password
    password: lifeofpi
    # the JDBC URL; the database is called DWGettingStarted
    url: jdbc:mysql://localhost:3306/GoogleDictionary
    properties:
      charSet: UTF-8
      characterEncoding: UTF-8
      useUnicode: true
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    maxWaitForConnection: 1s
    validationQuery: "/* DropWizard Health Check */ SELECT 1"
    minSize: 5
    maxSize: 25
    checkConnectionWhileIdle: false
    checkConnectionOnBorrow: true


#API settings
#API URL
apiURL: https://openexchangerates.org/api/latest.json
#API key
apiKey: <Your API key>

#Jersey client settings
jerseyClient:
    #The maximum idle time for a connection, once established.
    timeout: 512ms
    #The size of the work queue of the pool used for asynchronous requests.
    #Additional threads will be spawn only if the queue is reached its maximum size.
    workQueueSize: 16

